runtime: python39

env_variables:
  MAIL_USER: "info1@bizmowa.com"
  MAIL_PASSWORD: "Sl05936623"
  FLASK_SECRET_KEY: "meeting-scheduler-2025"
  BASE_URL: "https://bizmowa-mtg-jp.an.r.appspot.com"

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
