runtime: python39
service: default
env: standard
instance_class: F2

env_variables:
  MAIL_USER: "info1@bizmowa.com"
  MAIL_PASSWORD: "Sl05936623"
  FLASK_SECRET_KEY: "meeting-scheduler-2025"
  BASE_URL: "https://bizmowa-mtg-jp.an.r.appspot.com"
  GAE_ENV: "standard"
  DEBUG: "True"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
