name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        project_id: bizmowa-project-unique
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v1
